src/main/java/Seoul_Milk/sm_server/login/controller/JoinController.java
src/main/java/Seoul_Milk/sm_server/login/controller/ReissueController.java
src/main/java/Seoul_Milk/sm_server/login/dto/JoinDTO.java
src/main/java/Seoul_Milk/sm_server/login/entity/MemberEntity.java
src/main/resources/application.yml

✨ 스웨거 설정, 배포 스크립트 수정

---

build.gradle
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceFile/entity/TaxInvoiceFile.java
src/main/java/Seoul_Milk/sm_server/global/config/AwsS3Config.java
src/main/java/Seoul_Milk/sm_server/global/upload/controller/UploadController.java
src/main/java/Seoul_Milk/sm_server/global/upload/service/AwsS3Service.java
src/main/java/Seoul_Milk/sm_server/global/upload/util/AwsS3Util.java
src/main/resources/application.yml

✨ 파일 업로드 기능 추가

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/dto/BoundingPoly.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/dto/OcrField.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/dto/Vertex.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/infrastructure/ClovaOcrApi.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/service/OcrDataExtractor.java
src/main/java/Seoul_Milk/sm_server/global/exception/ErrorCode.java

🐛 OCR로 부가 정보 추출

---

src/main/java/Seoul_Milk/sm_server/global/config/SecurityConfig.java
src/main/java/Seoul_Milk/sm_server/global/exception/ErrorCode.java
src/main/java/Seoul_Milk/sm_server/global/exception/custom/CustomAccessDeniedHandler.java
src/main/java/Seoul_Milk/sm_server/global/exception/custom/CustomAuthenticationEntryPoint.java
src/main/java/Seoul_Milk/sm_server/global/jwt/LoginFilter.java
src/main/java/Seoul_Milk/sm_server/login/controller/AuthController.java
src/main/java/Seoul_Milk/sm_server/login/controller/JoinController.java
src/main/java/Seoul_Milk/sm_server/login/controller/MemberController.java
src/main/java/Seoul_Milk/sm_server/login/dto/request/JoinDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/request/LoginRequestDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/request/TestUpdateRoleDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/request/UpdatePwDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/request/UpdateRoleDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/response/LoginResponseDTO.java
src/main/java/Seoul_Milk/sm_server/login/dto/response/MemberResponse.java
src/main/java/Seoul_Milk/sm_server/login/entity/MemberEntity.java
src/main/java/Seoul_Milk/sm_server/login/service/JoinService.java
src/main/java/Seoul_Milk/sm_server/login/service/MemberService.java
src/main/java/Seoul_Milk/sm_server/login/service/MemberServiceImpl.java

✨ 권한 설정 기능

---

build.gradle
src/main/java/Seoul_Milk/sm_server/SM_serverApplication.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/global/config/QueryDSLConfig.java
src/main/java/Seoul_Milk/sm_server/login/entity/MemberEntity.java

✨ 내 업무 조회 기능

---

build.gradle
src/main/java/Seoul_Milk/sm_server/SM_serverApplication.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/enumClass/ProcessStatus.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/enums/ProcessStatus.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/service/OcrDataExtractor.java
src/main/java/Seoul_Milk/sm_server/global/config/QueryDSLConfig.java
src/main/java/Seoul_Milk/sm_server/login/entity/MemberEntity.java

🐛 OCR 데이터 처리 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/global/exception/ErrorCode.java

🐛 내 업무 조회 검색 조건 수정, 최적화

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceJpaRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/controller/TaxValidationController.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/dto/TestDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationService.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/thread/RequestThread.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/thread/RequestThreadManager.java
src/main/java/Seoul_Milk/sm_server/global/config/SecurityConfig.java

🐛 진위여부 판단 스레드 문제 해결

---

src/main/java/Seoul_Milk/sm_server/global/clovaOcr/infrastructure/ClovaOcrApi.java
src/main/java/Seoul_Milk/sm_server/global/exception/ErrorCode.java
src/main/java/Seoul_Milk/sm_server/global/upload/util/AwsS3Util.java

🐛 OCR에 PDF 파일 변환하지 못하는 문제 해결

---

build.gradle
src/main/java/Seoul_Milk/sm_server/domain/image/controller/ImageController.java
src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageRequestDTO.java
src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/image/entity/Image.java
src/main/java/Seoul_Milk/sm_server/domain/image/repository/ImageJpaRepository.java
src/main/java/Seoul_Milk/sm_server/domain/image/repository/ImageRepository.java
src/main/java/Seoul_Milk/sm_server/domain/image/repository/ImageRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/image/service/ImageService.java
src/main/java/Seoul_Milk/sm_server/domain/image/service/ImageServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceFile/repository/TaxInvoiceFileRepository.java
src/main/java/Seoul_Milk/sm_server/global/config/AwsS3Config.java
src/main/java/Seoul_Milk/sm_server/global/exception/ErrorCode.java
src/main/java/Seoul_Milk/sm_server/global/upload/service/AwsS3Service.java
src/main/java/Seoul_Milk/sm_server/global/util/CustomMultipartFile.java
src/main/java/Seoul_Milk/sm_server/login/entity/MemberEntity.java

✨ 이미지 임시저장 기능

---

src/main/java/Seoul_Milk/sm_server/domain/taxValidation/enums/CodefParameters.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/thread/RequestThread.java

🐛 진위여부 파악 api 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryDTO.java

✨ RE_02 조회 모달에 url응답 추가

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/enums/MaxSearchLimit.java

✨ RE_01 조회 API 최대 100개까지만 조회되도록 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryDTO.java

✨ RE_02 승인모달에 세액 추가

---

src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageResponseDTO.java

✨ fi_01 임시저장된 이미지 전체 조회 api 응답값에 파일id 추가

---

src/main/java/Seoul_Milk/sm_server/domain/image/entity/Image.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/enums/ArapType.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/dto/TemplateOcrField.java
src/main/java/Seoul_Milk/sm_server/global/clovaOcr/service/OcrDataExtractor.java
src/main/resources/application.yml

♻️ CLOVA OCR 유형 Template로 변경 

---

src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java

✨ 검증하기 API에 금액관련 처리

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/enums/CodefResponseCode.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java

✨ 진위여부 검증 api 에러처리 추가 

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java

✨ RE_01 공급자/공급받는자 검색 옵션 업그레이드

---

src/main/java/Seoul_Milk/sm_server/domain/image/controller/ImageController.java
src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageRequestDTO.java
src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/image/entity/Image.java
src/main/java/Seoul_Milk/sm_server/domain/image/service/ImageService.java
src/main/java/Seoul_Milk/sm_server/domain/image/service/ImageServiceImpl.java

🐛 임시저장 기능 보완 (모바일 버전 적용) chore 사소한 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java

🐛 RE_01검색 API에서 임시저장 여부 확인로직 제거

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java

🐛 WO_01 내 업무 조회 검색옵션 변경 시작날짜 ~ 특정날짜 까지 검색되도록 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceFile/entity/TaxInvoiceFile.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxValidation/thread/RequestThread.java

🐛 TaxInvoice에 승인번호가 같은 세금계산서 업로드 시 처리로직 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/controller/TaxInvoiceController.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java

🐛 내 업무 조회 검색조건 변경

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java

🐛 RE 데이터 조회 부분 임시저장 여부 삭제

---

src/main/java/Seoul_Milk/sm_server/domain/taxValidation/service/TaxValidationServiceImpl.java

🐛진위여부 검증 api UNAPPROVED(승인실패) 처리 추가

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryResponseDTO.java

🐛 WO, RE 조회 쪽 공급자, 공급받는자에 회사명들어오게 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryResponseDTO.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/service/TaxInvoiceValidationServiceImpl.java

🐛 RE_01 조회 추가 수정

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryResponseDTO.java

🐛공급자, 공급받는자 매핑 오류 해결 

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java

🐛 검증 내역에 최신순 정렬이 안 되는 문제 해결

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoiceValidationHistory/dto/TaxInvoiceValidationHistoryResponseDTO.java

🐛 RE페이지에서 공급자 공급받는자 바뀌어서 들어간 현상 해결

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java

🐛 업무 조회 검색 부분 업데이트

---

src/main/java/Seoul_Milk/sm_server/domain/image/controller/ImageController.java
src/main/java/Seoul_Milk/sm_server/domain/image/dto/ImageRequestDTO.java
src/main/java/Seoul_Milk/sm_server/domain/image/repository/ImageRepositoryImpl.java

- #138 
---
---
해당 api request body 매핑이 안됨 그래서 쿼리 파라미터로 바꾸었

🐛 fi_01 임시저장 해제 404에러 현상 해결하기

---

src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/dto/TaxInvoiceResponseDTO.java

🐛WO 조회하기 api응답에서 작성한 사람 이름 추가

---

src/main/java/Seoul_Milk/sm_server/SM_serverApplication.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/entity/TaxInvoice.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceJpaRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepository.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/repository/TaxInvoiceRepositoryImpl.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceService.java
src/main/java/Seoul_Milk/sm_server/domain/taxInvoice/service/TaxInvoiceServiceImpl.java

✨ 세금계산서는 1년 동안만 저장되도록 설정

---

src/main/java/Seoul_Milk/sm_server/global/config/SecurityConfig.java
src/main/java/Seoul_Milk/sm_server/global/security/auth/controller/AuthController.java
src/main/java/Seoul_Milk/sm_server/global/security/jwt/CustomLogoutFilter.java

✨ LO_04 로그아웃 기능 구현
